[book]
authors = ["Thomas Jejkal", "Andreas Pfeil"]
language = "en"
multilingual = false
src = "src"
title = "FAIR DO Cookbook"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
no-section-label = true
additional-css = ["hierarchical_numbered_lists.css"]